// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	KmsEncryptRequest
	KmsEncryptResponse
	EncryptRequest
	EncryptResponse
	KmsDecryptRequest
	KmsDecryptResponse
	DecryptRequest
	DecryptResponse
	SignRequest
	SignResponse
	VerifyRequest
	VerifyResponse
	HmacRequest
	HmacResponse
	GenerateRandomRequest
	GenerateRandomResponse
	HashRequest
	HashResponse
	GenerateDataKeyRequest
	GenerateDataKeyResponse
	GetPublicKeyRequest
	GetPublicKeyResponse
	Error
*/
package api

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KmsEncryptRequest struct {
	KeyId     string `protobuf:"bytes,1,opt,name=KeyId" json:"KeyId,omitempty"`
	Plaintext []byte `protobuf:"bytes,2,opt,name=Plaintext,proto3" json:"Plaintext,omitempty"`
	Aad       []byte `protobuf:"bytes,3,opt,name=Aad,proto3" json:"Aad,omitempty"`
}

func (m *KmsEncryptRequest) Reset()                    { *m = KmsEncryptRequest{} }
func (m *KmsEncryptRequest) String() string            { return proto.CompactTextString(m) }
func (*KmsEncryptRequest) ProtoMessage()               {}
func (*KmsEncryptRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type KmsEncryptResponse struct {
	KeyId          string `protobuf:"bytes,1,opt,name=KeyId" json:"KeyId,omitempty"`
	CiphertextBlob []byte `protobuf:"bytes,2,opt,name=CiphertextBlob,proto3" json:"CiphertextBlob,omitempty"`
	RequestId      string `protobuf:"bytes,3,opt,name=RequestId" json:"RequestId,omitempty"`
}

func (m *KmsEncryptResponse) Reset()                    { *m = KmsEncryptResponse{} }
func (m *KmsEncryptResponse) String() string            { return proto.CompactTextString(m) }
func (*KmsEncryptResponse) ProtoMessage()               {}
func (*KmsEncryptResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type EncryptRequest struct {
	KeyId       string `protobuf:"bytes,1,opt,name=KeyId" json:"KeyId,omitempty"`
	Plaintext   []byte `protobuf:"bytes,2,opt,name=Plaintext,proto3" json:"Plaintext,omitempty"`
	Algorithm   string `protobuf:"bytes,3,opt,name=Algorithm" json:"Algorithm,omitempty"`
	Aad         []byte `protobuf:"bytes,4,opt,name=Aad,proto3" json:"Aad,omitempty"`
	Iv          []byte `protobuf:"bytes,5,opt,name=Iv,proto3" json:"Iv,omitempty"`
	PaddingMode string `protobuf:"bytes,6,opt,name=PaddingMode" json:"PaddingMode,omitempty"`
}

func (m *EncryptRequest) Reset()                    { *m = EncryptRequest{} }
func (m *EncryptRequest) String() string            { return proto.CompactTextString(m) }
func (*EncryptRequest) ProtoMessage()               {}
func (*EncryptRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type EncryptResponse struct {
	KeyId          string `protobuf:"bytes,1,opt,name=KeyId" json:"KeyId,omitempty"`
	CiphertextBlob []byte `protobuf:"bytes,2,opt,name=CiphertextBlob,proto3" json:"CiphertextBlob,omitempty"`
	Iv             []byte `protobuf:"bytes,3,opt,name=Iv,proto3" json:"Iv,omitempty"`
	RequestId      string `protobuf:"bytes,4,opt,name=RequestId" json:"RequestId,omitempty"`
	Algorithm      string `protobuf:"bytes,5,opt,name=Algorithm" json:"Algorithm,omitempty"`
	PaddingMode    string `protobuf:"bytes,6,opt,name=PaddingMode" json:"PaddingMode,omitempty"`
}

func (m *EncryptResponse) Reset()                    { *m = EncryptResponse{} }
func (m *EncryptResponse) String() string            { return proto.CompactTextString(m) }
func (*EncryptResponse) ProtoMessage()               {}
func (*EncryptResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type KmsDecryptRequest struct {
	CiphertextBlob []byte `protobuf:"bytes,1,opt,name=CiphertextBlob,proto3" json:"CiphertextBlob,omitempty"`
	Aad            []byte `protobuf:"bytes,2,opt,name=Aad,proto3" json:"Aad,omitempty"`
}

func (m *KmsDecryptRequest) Reset()                    { *m = KmsDecryptRequest{} }
func (m *KmsDecryptRequest) String() string            { return proto.CompactTextString(m) }
func (*KmsDecryptRequest) ProtoMessage()               {}
func (*KmsDecryptRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type KmsDecryptResponse struct {
	KeyId     string `protobuf:"bytes,1,opt,name=KeyId" json:"KeyId,omitempty"`
	Plaintext []byte `protobuf:"bytes,2,opt,name=Plaintext,proto3" json:"Plaintext,omitempty"`
	RequestId string `protobuf:"bytes,3,opt,name=RequestId" json:"RequestId,omitempty"`
}

func (m *KmsDecryptResponse) Reset()                    { *m = KmsDecryptResponse{} }
func (m *KmsDecryptResponse) String() string            { return proto.CompactTextString(m) }
func (*KmsDecryptResponse) ProtoMessage()               {}
func (*KmsDecryptResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type DecryptRequest struct {
	CiphertextBlob []byte `protobuf:"bytes,1,opt,name=CiphertextBlob,proto3" json:"CiphertextBlob,omitempty"`
	KeyId          string `protobuf:"bytes,2,opt,name=KeyId" json:"KeyId,omitempty"`
	Algorithm      string `protobuf:"bytes,3,opt,name=Algorithm" json:"Algorithm,omitempty"`
	Aad            []byte `protobuf:"bytes,4,opt,name=Aad,proto3" json:"Aad,omitempty"`
	Iv             []byte `protobuf:"bytes,5,opt,name=Iv,proto3" json:"Iv,omitempty"`
	PaddingMode    string `protobuf:"bytes,6,opt,name=PaddingMode" json:"PaddingMode,omitempty"`
}

func (m *DecryptRequest) Reset()                    { *m = DecryptRequest{} }
func (m *DecryptRequest) String() string            { return proto.CompactTextString(m) }
func (*DecryptRequest) ProtoMessage()               {}
func (*DecryptRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type DecryptResponse struct {
	KeyId       string `protobuf:"bytes,1,opt,name=KeyId" json:"KeyId,omitempty"`
	Plaintext   []byte `protobuf:"bytes,2,opt,name=Plaintext,proto3" json:"Plaintext,omitempty"`
	RequestId   string `protobuf:"bytes,3,opt,name=RequestId" json:"RequestId,omitempty"`
	Algorithm   string `protobuf:"bytes,4,opt,name=Algorithm" json:"Algorithm,omitempty"`
	PaddingMode string `protobuf:"bytes,5,opt,name=PaddingMode" json:"PaddingMode,omitempty"`
}

func (m *DecryptResponse) Reset()                    { *m = DecryptResponse{} }
func (m *DecryptResponse) String() string            { return proto.CompactTextString(m) }
func (*DecryptResponse) ProtoMessage()               {}
func (*DecryptResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type SignRequest struct {
	KeyId       string `protobuf:"bytes,1,opt,name=KeyId" json:"KeyId,omitempty"`
	Digest      []byte `protobuf:"bytes,2,opt,name=Digest,proto3" json:"Digest,omitempty"`
	Algorithm   string `protobuf:"bytes,3,opt,name=Algorithm" json:"Algorithm,omitempty"`
	Message     []byte `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	MessageType string `protobuf:"bytes,5,opt,name=MessageType" json:"MessageType,omitempty"`
}

func (m *SignRequest) Reset()                    { *m = SignRequest{} }
func (m *SignRequest) String() string            { return proto.CompactTextString(m) }
func (*SignRequest) ProtoMessage()               {}
func (*SignRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type SignResponse struct {
	KeyId       string `protobuf:"bytes,1,opt,name=KeyId" json:"KeyId,omitempty"`
	Signature   []byte `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	RequestId   string `protobuf:"bytes,3,opt,name=RequestId" json:"RequestId,omitempty"`
	Algorithm   string `protobuf:"bytes,4,opt,name=Algorithm" json:"Algorithm,omitempty"`
	MessageType string `protobuf:"bytes,5,opt,name=MessageType" json:"MessageType,omitempty"`
}

func (m *SignResponse) Reset()                    { *m = SignResponse{} }
func (m *SignResponse) String() string            { return proto.CompactTextString(m) }
func (*SignResponse) ProtoMessage()               {}
func (*SignResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type VerifyRequest struct {
	KeyId       string `protobuf:"bytes,1,opt,name=KeyId" json:"KeyId,omitempty"`
	Digest      []byte `protobuf:"bytes,2,opt,name=Digest,proto3" json:"Digest,omitempty"`
	Signature   []byte `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Algorithm   string `protobuf:"bytes,4,opt,name=Algorithm" json:"Algorithm,omitempty"`
	Message     []byte `protobuf:"bytes,5,opt,name=Message,proto3" json:"Message,omitempty"`
	MessageType string `protobuf:"bytes,6,opt,name=MessageType" json:"MessageType,omitempty"`
}

func (m *VerifyRequest) Reset()                    { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string            { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()               {}
func (*VerifyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type VerifyResponse struct {
	KeyId       string `protobuf:"bytes,1,opt,name=KeyId" json:"KeyId,omitempty"`
	Value       bool   `protobuf:"varint,2,opt,name=Value" json:"Value,omitempty"`
	RequestId   string `protobuf:"bytes,3,opt,name=RequestId" json:"RequestId,omitempty"`
	Algorithm   string `protobuf:"bytes,4,opt,name=Algorithm" json:"Algorithm,omitempty"`
	MessageType string `protobuf:"bytes,5,opt,name=MessageType" json:"MessageType,omitempty"`
}

func (m *VerifyResponse) Reset()                    { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string            { return proto.CompactTextString(m) }
func (*VerifyResponse) ProtoMessage()               {}
func (*VerifyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type HmacRequest struct {
	KeyId   string `protobuf:"bytes,1,opt,name=KeyId" json:"KeyId,omitempty"`
	Message []byte `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (m *HmacRequest) Reset()                    { *m = HmacRequest{} }
func (m *HmacRequest) String() string            { return proto.CompactTextString(m) }
func (*HmacRequest) ProtoMessage()               {}
func (*HmacRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type HmacResponse struct {
	KeyId     string `protobuf:"bytes,1,opt,name=KeyId" json:"KeyId,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	RequestId string `protobuf:"bytes,3,opt,name=RequestId" json:"RequestId,omitempty"`
}

func (m *HmacResponse) Reset()                    { *m = HmacResponse{} }
func (m *HmacResponse) String() string            { return proto.CompactTextString(m) }
func (*HmacResponse) ProtoMessage()               {}
func (*HmacResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type GenerateRandomRequest struct {
	Length int32 `protobuf:"varint,1,opt,name=Length" json:"Length,omitempty"`
}

func (m *GenerateRandomRequest) Reset()                    { *m = GenerateRandomRequest{} }
func (m *GenerateRandomRequest) String() string            { return proto.CompactTextString(m) }
func (*GenerateRandomRequest) ProtoMessage()               {}
func (*GenerateRandomRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type GenerateRandomResponse struct {
	Random    []byte `protobuf:"bytes,1,opt,name=Random,proto3" json:"Random,omitempty"`
	RequestId string `protobuf:"bytes,2,opt,name=RequestId" json:"RequestId,omitempty"`
}

func (m *GenerateRandomResponse) Reset()                    { *m = GenerateRandomResponse{} }
func (m *GenerateRandomResponse) String() string            { return proto.CompactTextString(m) }
func (*GenerateRandomResponse) ProtoMessage()               {}
func (*GenerateRandomResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type HashRequest struct {
	Message   []byte `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Algorithm string `protobuf:"bytes,2,opt,name=Algorithm" json:"Algorithm,omitempty"`
}

func (m *HashRequest) Reset()                    { *m = HashRequest{} }
func (m *HashRequest) String() string            { return proto.CompactTextString(m) }
func (*HashRequest) ProtoMessage()               {}
func (*HashRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type HashResponse struct {
	Digest    []byte `protobuf:"bytes,1,opt,name=Digest,proto3" json:"Digest,omitempty"`
	RequestId string `protobuf:"bytes,3,opt,name=RequestId" json:"RequestId,omitempty"`
}

func (m *HashResponse) Reset()                    { *m = HashResponse{} }
func (m *HashResponse) String() string            { return proto.CompactTextString(m) }
func (*HashResponse) ProtoMessage()               {}
func (*HashResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type GenerateDataKeyRequest struct {
	KeyId         string `protobuf:"bytes,1,opt,name=KeyId" json:"KeyId,omitempty"`
	Algorithm     string `protobuf:"bytes,2,opt,name=Algorithm" json:"Algorithm,omitempty"`
	NumberOfBytes int32  `protobuf:"varint,3,opt,name=NumberOfBytes" json:"NumberOfBytes,omitempty"`
	Aad           []byte `protobuf:"bytes,4,opt,name=Aad,proto3" json:"Aad,omitempty"`
}

func (m *GenerateDataKeyRequest) Reset()                    { *m = GenerateDataKeyRequest{} }
func (m *GenerateDataKeyRequest) String() string            { return proto.CompactTextString(m) }
func (*GenerateDataKeyRequest) ProtoMessage()               {}
func (*GenerateDataKeyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type GenerateDataKeyResponse struct {
	KeyId          string `protobuf:"bytes,1,opt,name=KeyId" json:"KeyId,omitempty"`
	Iv             []byte `protobuf:"bytes,2,opt,name=Iv,proto3" json:"Iv,omitempty"`
	Plaintext      []byte `protobuf:"bytes,3,opt,name=Plaintext,proto3" json:"Plaintext,omitempty"`
	CiphertextBlob []byte `protobuf:"bytes,4,opt,name=CiphertextBlob,proto3" json:"CiphertextBlob,omitempty"`
	RequestId      string `protobuf:"bytes,5,opt,name=RequestId" json:"RequestId,omitempty"`
	Algorithm      string `protobuf:"bytes,6,opt,name=Algorithm" json:"Algorithm,omitempty"`
}

func (m *GenerateDataKeyResponse) Reset()                    { *m = GenerateDataKeyResponse{} }
func (m *GenerateDataKeyResponse) String() string            { return proto.CompactTextString(m) }
func (*GenerateDataKeyResponse) ProtoMessage()               {}
func (*GenerateDataKeyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type GetPublicKeyRequest struct {
	KeyId string `protobuf:"bytes,1,opt,name=KeyId" json:"KeyId,omitempty"`
}

func (m *GetPublicKeyRequest) Reset()                    { *m = GetPublicKeyRequest{} }
func (m *GetPublicKeyRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPublicKeyRequest) ProtoMessage()               {}
func (*GetPublicKeyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type GetPublicKeyResponse struct {
	KeyId     string `protobuf:"bytes,1,opt,name=KeyId" json:"KeyId,omitempty"`
	PublicKey string `protobuf:"bytes,2,opt,name=PublicKey" json:"PublicKey,omitempty"`
	RequestId string `protobuf:"bytes,3,opt,name=RequestId" json:"RequestId,omitempty"`
}

func (m *GetPublicKeyResponse) Reset()                    { *m = GetPublicKeyResponse{} }
func (m *GetPublicKeyResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPublicKeyResponse) ProtoMessage()               {}
func (*GetPublicKeyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type Error struct {
	StatusCode   int32  `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	ErrorCode    string `protobuf:"bytes,2,opt,name=ErrorCode" json:"ErrorCode,omitempty"`
	ErrorMessage string `protobuf:"bytes,3,opt,name=ErrorMessage" json:"ErrorMessage,omitempty"`
	RequestId    string `protobuf:"bytes,4,opt,name=RequestId" json:"RequestId,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func init() {
	proto.RegisterType((*KmsEncryptRequest)(nil), "KmsEncryptRequest")
	proto.RegisterType((*KmsEncryptResponse)(nil), "KmsEncryptResponse")
	proto.RegisterType((*EncryptRequest)(nil), "EncryptRequest")
	proto.RegisterType((*EncryptResponse)(nil), "EncryptResponse")
	proto.RegisterType((*KmsDecryptRequest)(nil), "KmsDecryptRequest")
	proto.RegisterType((*KmsDecryptResponse)(nil), "KmsDecryptResponse")
	proto.RegisterType((*DecryptRequest)(nil), "DecryptRequest")
	proto.RegisterType((*DecryptResponse)(nil), "DecryptResponse")
	proto.RegisterType((*SignRequest)(nil), "SignRequest")
	proto.RegisterType((*SignResponse)(nil), "SignResponse")
	proto.RegisterType((*VerifyRequest)(nil), "VerifyRequest")
	proto.RegisterType((*VerifyResponse)(nil), "VerifyResponse")
	proto.RegisterType((*HmacRequest)(nil), "HmacRequest")
	proto.RegisterType((*HmacResponse)(nil), "HmacResponse")
	proto.RegisterType((*GenerateRandomRequest)(nil), "GenerateRandomRequest")
	proto.RegisterType((*GenerateRandomResponse)(nil), "GenerateRandomResponse")
	proto.RegisterType((*HashRequest)(nil), "HashRequest")
	proto.RegisterType((*HashResponse)(nil), "HashResponse")
	proto.RegisterType((*GenerateDataKeyRequest)(nil), "GenerateDataKeyRequest")
	proto.RegisterType((*GenerateDataKeyResponse)(nil), "GenerateDataKeyResponse")
	proto.RegisterType((*GetPublicKeyRequest)(nil), "GetPublicKeyRequest")
	proto.RegisterType((*GetPublicKeyResponse)(nil), "GetPublicKeyResponse")
	proto.RegisterType((*Error)(nil), "Error")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 687 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0x4f, 0x6f, 0xd3, 0x4c,
	0x10, 0xc6, 0xb5, 0x4e, 0xec, 0xf7, 0xcd, 0x24, 0x4d, 0xc1, 0x94, 0xe0, 0x43, 0x85, 0xaa, 0x15,
	0x42, 0x95, 0x90, 0xe0, 0xc0, 0x99, 0x43, 0xdb, 0x44, 0x6d, 0x14, 0x52, 0x22, 0x17, 0x55, 0xe2,
	0xc6, 0x26, 0xde, 0x38, 0x96, 0x12, 0xdb, 0xd8, 0xeb, 0x0a, 0xdf, 0x91, 0xf8, 0x04, 0x5c, 0x38,
	0x21, 0x21, 0x71, 0xe6, 0xc2, 0x91, 0x03, 0xdf, 0x0c, 0xd9, 0xbb, 0xfe, 0xdf, 0xda, 0x52, 0x69,
	0x6e, 0x99, 0x27, 0xeb, 0x99, 0xdf, 0x3c, 0x3b, 0xde, 0x35, 0x74, 0x88, 0x6b, 0x3d, 0x77, 0x3d,
	0x87, 0x39, 0xf8, 0x1d, 0xdc, 0x9f, 0x6c, 0xfc, 0x91, 0xbd, 0xf0, 0x42, 0x97, 0xe9, 0xf4, 0x43,
	0x40, 0x7d, 0xa6, 0xee, 0x81, 0x3c, 0xa1, 0xe1, 0xd8, 0xd0, 0xd0, 0x01, 0x3a, 0xec, 0xe8, 0x3c,
	0x50, 0xf7, 0xa1, 0x33, 0x5b, 0x13, 0xcb, 0x66, 0xf4, 0x23, 0xd3, 0xa4, 0x03, 0x74, 0xd8, 0xd3,
	0x33, 0x41, 0xbd, 0x07, 0xad, 0x23, 0x62, 0x68, 0xad, 0x58, 0x8f, 0x7e, 0x62, 0x17, 0xd4, 0x7c,
	0x6a, 0xdf, 0x75, 0x6c, 0x9f, 0xde, 0x90, 0xfb, 0x29, 0xf4, 0x4f, 0x2c, 0x77, 0x45, 0xbd, 0x28,
	0xd7, 0xf1, 0xda, 0x99, 0x8b, 0x02, 0x25, 0x35, 0x62, 0x10, 0x90, 0x63, 0x5e, 0xab, 0xa3, 0x67,
	0x02, 0xfe, 0x81, 0xa0, 0x7f, 0x07, 0xad, 0xec, 0x43, 0xe7, 0x68, 0x6d, 0x3a, 0x9e, 0xc5, 0x56,
	0x9b, 0xa4, 0x48, 0x2a, 0x24, 0x8d, 0xb6, 0xd3, 0x46, 0xd5, 0x3e, 0x48, 0xe3, 0x2b, 0x4d, 0x8e,
	0x05, 0x69, 0x7c, 0xa5, 0x1e, 0x40, 0x77, 0x46, 0x0c, 0xc3, 0xb2, 0xcd, 0xa9, 0x63, 0x50, 0x4d,
	0x89, 0x33, 0xe4, 0x25, 0xfc, 0x1b, 0xc1, 0xee, 0xdd, 0x1a, 0xc3, 0x19, 0x5a, 0x29, 0x43, 0xc1,
	0xa8, 0x76, 0xc9, 0xa8, 0x62, 0x87, 0x72, 0xb9, 0xc3, 0x66, 0xfe, 0x69, 0x3c, 0x35, 0x43, 0x5a,
	0xb0, 0xba, 0x8a, 0x8a, 0xae, 0x45, 0x15, 0x06, 0x4a, 0xd9, 0xa4, 0x2c, 0xe3, 0x49, 0x49, 0xd3,
	0xd5, 0x1a, 0xd2, 0xb8, 0x75, 0x35, 0xf3, 0xf1, 0x13, 0x41, 0xff, 0x96, 0xd0, 0x29, 0x8c, 0x54,
	0x82, 0xd9, 0xf2, 0xa4, 0x7c, 0x47, 0xb0, 0xbb, 0x75, 0x63, 0x8a, 0x7d, 0xb4, 0x1b, 0xe6, 0x41,
	0xae, 0x52, 0x7e, 0x41, 0xd0, 0xbd, 0xb0, 0x4c, 0xbb, 0xfe, 0xad, 0x1b, 0x80, 0x32, 0xb4, 0x4c,
	0xea, 0x27, 0x78, 0x22, 0x6a, 0x70, 0x51, 0x83, 0xff, 0xa6, 0xd4, 0xf7, 0x89, 0x49, 0x85, 0x93,
	0x49, 0x18, 0x71, 0x89, 0x9f, 0x6f, 0x43, 0x37, 0xe5, 0xca, 0x49, 0xf8, 0x1b, 0x82, 0x1e, 0xe7,
	0x6a, 0xb2, 0x2e, 0x5a, 0x45, 0x58, 0xe0, 0xd1, 0xc4, 0xba, 0x54, 0xf8, 0x57, 0xeb, 0x1a, 0x10,
	0x7f, 0x21, 0xd8, 0xb9, 0xa4, 0x9e, 0xb5, 0x0c, 0x6f, 0x6d, 0x5e, 0xc6, 0xde, 0xba, 0x86, 0xbd,
	0x86, 0x2e, 0x67, 0xad, 0x5c, 0x6b, 0xad, 0x52, 0xe5, 0xfe, 0x8a, 0xa0, 0x9f, 0x70, 0xd7, 0x9a,
	0xbb, 0x07, 0xf2, 0x25, 0x59, 0x07, 0xdc, 0xd8, 0xff, 0x75, 0x1e, 0x6c, 0xd9, 0xd4, 0x57, 0xd0,
	0x3d, 0xdb, 0x90, 0x45, 0xbd, 0xa3, 0xb9, 0xee, 0xa5, 0x42, 0xf7, 0xf8, 0x3d, 0xf4, 0xf8, 0xe3,
	0xdb, 0x9a, 0x1a, 0xfc, 0x02, 0x1e, 0x9e, 0x52, 0x9b, 0x7a, 0x84, 0x51, 0x9d, 0xd8, 0x86, 0xb3,
	0x49, 0x50, 0x07, 0xa0, 0xbc, 0xa6, 0xb6, 0xc9, 0x56, 0x71, 0x2d, 0x59, 0x17, 0x11, 0x3e, 0x87,
	0x41, 0xf9, 0x01, 0x01, 0x37, 0x00, 0x85, 0x2b, 0xe2, 0xe4, 0x12, 0x51, 0x11, 0x40, 0x2a, 0x03,
	0x8c, 0xa0, 0x7b, 0x46, 0xfc, 0x55, 0x52, 0x36, 0xe7, 0x05, 0x2a, 0x4e, 0x42, 0x61, 0x2b, 0xa4,
	0xd2, 0x56, 0xe0, 0x21, 0xf4, 0x78, 0x9a, 0x0c, 0x46, 0x4c, 0x29, 0x2a, 0x4f, 0x69, 0x8d, 0x1b,
	0x9f, 0x50, 0xd6, 0xdd, 0x90, 0x30, 0x32, 0xa1, 0x61, 0xe3, 0xfd, 0x7d, 0x33, 0x94, 0xfa, 0x04,
	0x76, 0xce, 0x83, 0xcd, 0x9c, 0x7a, 0x6f, 0x96, 0xc7, 0x21, 0xa3, 0x7e, 0x5c, 0x50, 0xd6, 0x8b,
	0x62, 0xf5, 0x74, 0xc6, 0x7f, 0x10, 0x3c, 0xaa, 0x60, 0xd4, 0x8e, 0x00, 0x3f, 0xcf, 0xa5, 0xfc,
	0xad, 0x9b, 0x9d, 0xc1, 0xad, 0xf2, 0x19, 0x5c, 0xbd, 0x6b, 0xda, 0xcd, 0x1f, 0x39, 0x72, 0xed,
	0xbb, 0xa1, 0x94, 0x37, 0xe4, 0x19, 0x3c, 0x38, 0xa5, 0x6c, 0x16, 0xcc, 0xd7, 0xd6, 0xa2, 0xc9,
	0x46, 0xbc, 0x82, 0xbd, 0xe2, 0xe2, 0xc6, 0x0b, 0x26, 0x59, 0x9a, 0x98, 0x9e, 0x0a, 0x0d, 0x3b,
	0xfc, 0x19, 0x81, 0x3c, 0xf2, 0x3c, 0xc7, 0x53, 0x1f, 0x03, 0x5c, 0x30, 0xc2, 0x02, 0xff, 0x24,
	0xba, 0x4b, 0xf8, 0x90, 0xe7, 0x94, 0x28, 0x4f, 0xbc, 0x30, 0xfe, 0x5b, 0x54, 0x49, 0x05, 0x15,
	0x43, 0x2f, 0x0e, 0x92, 0x61, 0xe5, 0x85, 0x0a, 0x5a, 0xfd, 0xa7, 0xcf, 0x5c, 0x89, 0xbf, 0x7b,
	0x5f, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x24, 0x10, 0x28, 0xa2, 0x04, 0x0b, 0x00, 0x00,
}
